# **EDA -- Exploratory Data Analysis**

---

70% -- EDA  ||   30% -- Etc.

1. Understanding the data

2. Cleaning the Data: 
        -- Preprocessing of Data
        
        -- Handle the missing values | remove noise ,outliers and duplicates
        -- Incorrect data type, renaming columns
        -- encoding and scaling

3. Feature engineering
4. Statistical analysis
5. Visualisation
6. Hypothesis Testing

---
Making our data Model ready

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
data = pd.read_csv('BBData.csv')
df = pd.DataFrame(data)
df.head(5)

,index,product,category,sub_category,brand,sale_price,market_price,type,rating,description
0,1,Garlic Oil - Vegetarian Capsule 500 mg,Beauty & Hygiene,Hair Care,Sri Sri Ayurveda,220.0,220.0,Hair Oil & Serum,4.1,This Product contains Garlic Oil that is known...
1,2,Water Bottle - Orange,"Kitchen, Garden & Pets",Storage & Accessories,Mastercook,180.0,180.0,Water & Fridge Bottles,2.3,"Each product is microwave safe (without lid), ..."
2,3,"Brass Angle Deep - Plain, No.2",Cleaning & Household,Pooja Needs,Trm,119.0,250.0,Lamp & Lamp Oil,3.4,"A perfect gift for all occasions, be it your m..."
3,4,Cereal Flip Lid Container/Storage Jar - Assort...,Cleaning & Household,Bins & Bathroom Ware,Nakoda,149.0,176.0,"Laundry, Storage Baskets",3.7,Multipurpose container with an attractive desi...
4,5,Creme Soft Soap - For Hands & Body,Beauty & Hygiene,Bath & Hand Wash,Nivea,162.0,162.0,Bathing Bars & Soaps,4.4,Nivea Creme Soft Soap gives your skin the best...

In [3]:
# print no of rows and columns

print(df.shape)

(27555, 10)

In [4]:
df.isnull().sum()

index              0
product            1
category           0
sub_category       0
brand              1
sale_price         0
market_price       0
type               0
rating          8626
description      115
dtype: int64

In [5]:
df.columns

Index(['index', 'product', 'category', 'sub_category', 'brand', 'sale_price',
       'market_price', 'type', 'rating', 'description'],
      dtype='str')

In [6]:
df.sample(7)

,index,product,category,sub_category,brand,sale_price,market_price,type,rating,description
22207,22208,Eggless Chocolate Cake Mix,Gourmet & World Food,Cooking & Baking Needs,Nectar Valley,325.00,325.0,Flours & Pre-Mixes,NaN,Prepare this quick and easy Eggless Chocolate ...
25727,25728,Power 10 Formula WH Effector,Beauty & Hygiene,Skin Care,It's Skin,855.00,950.0,Face Care,4.0,Its Skin Power 10 Formula WH Effector helps to...
24852,24853,Smoked Back Bacon,"Eggs, Meat & Fish","Sausages, Bacon & Salami",Meatzza,350.00,350.0,Chicken Sausages,NaN,Meatzza Pork Bacon is made from farm raised Po...
1224,1225,Hazelnut Cold Brew Packs,Gourmet & World Food,Drinks & Beverages,Sleepy Owl,400.00,500.0,Coffee & Pre-Mix,NaN,1. This product is made from pure 100% Arabica...
22381,22382,Shower Gel - Refreshing Pulse For Men With Sea...,Beauty & Hygiene,Bath & Hand Wash,Fiama,283.57,398.0,Bath & Shower,4.2,"Enriched with sea minerals, the refreshing pul..."
11109,11110,Instant Coffee - Strong,Beverages,Coffee,Continental,635.00,635.0,Instant Coffee,4.2,"Established in 1995, CCL is Indias largest cof..."
19582,19583,"Energy Bars - Berry, 4+ Years, 100% Natural & ...",Snacks & Branded Foods,Breakfast Cereals,Timios,140.00,140.0,Chocolates,4.0,Timios Berry Energy Bars are made from 100% na...

In [7]:
df = df.drop(columns = 'index')
df.isnull().sum()

product            1
category           0
sub_category       0
brand              1
sale_price         0
market_price       0
type               0
rating          8626
description      115
dtype: int64

In [8]:
df = df.dropna(subset=['product'])

In [9]:
df['brand'] = df['brand'].fillna("Unknown")
df['brand'].info()

<class 'pandas.Series'>
Index: 27554 entries, 0 to 27554
Series name: brand
Non-Null Count  Dtype
--------------  -----
27554 non-null  str
dtypes: str(1)
memory usage: 430.5 KB

In [10]:
df['description'] = df['description'].fillna("Not Available")

In [11]:
df.isnull().sum()

product            0
category           0
sub_category       0
brand              0
sale_price         0
market_price       0
type               0
rating          8626
description        0
dtype: int64

In [12]:
df1 = df['rating'] = df.groupby(['brand' , 'category'])['rating'].transform(lambda x:x.fillna(x.mean))

In [13]:
df1

0        4.1
1        2.3
2        3.4
3        3.7
4        4.4
        ...
27550    3.9
27551    4.0
27552    3.8
27553    4.2
27554    4.5
Name: rating, Length: 27554, dtype: object

In [14]:
print(df.duplicated().sum())

354

In [15]:
df.drop_duplicates(inplace= True)

In [16]:
df.to_csv("EDA File Cleaned.csv")